### ISSUE TITLE
Are the "legacy voices" from Streamlabs covered with this?

### ISSUE THREAD

**Issue by LukasThyWalls** [chrisjp/tts#5]
Hello.

Anyone knows a way to test the Streamlabs "Legacy Voices"? I just look up with this and no one of the ones that work doesn't seems from them.

What is the API these voices come from?

Thanks!

**Comment by chrisjp** [comment]
I wasn't actually aware of those so called "Legacy Voices" when I made this. I suspect they were deprecated for quite some time and eventually removed from Streamlabs. Sorry but I don't know of any other APIs that have these voices available. And I don't even know what they were called so that I could search for them.

**Comment by LukasThyWalls** [comment]
Thanks anyway!

They were never deprecated, they are there for years and you can still use them right now for Twitch alerts and things like that, although as their name say they look like the "old" version (they don't have names, and only one per language) and maybe they wanna get rid of them but they never did because some people still use them...? idk.

Also, i don't find anywhere in the Streamlabs website where says from where the API voices comes from, not only the Legacy ones, also the "Polly" ones.

In any case, very nice project! Thanks!
